In [2]:
#Question 1
import numpy as np
arr=np.arange(start=2,stop=50,step=3)
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [3]:
#Question 2
list1=[]
list2=[]
n=5
list1=[int(item)for item in input("Enter the list 1 items: ").split()]
list2=[int(item)for item in input("Enter the list 2 items: ").split()]
print("The list 1 is:" ,list1)
print("The list 2 is:" ,list2)
print('')
arr1=np.array([list1])
print("The 1st numpy array is:" ,arr1)
print('')
arr2=np.array([list2])
print("The 2nd numpy array is:" ,arr2)
print('')
arr3=np.concatenate((arr1,arr2),axis=1)
print("The concatenation of 2 arrays is:" ,arr3)
print('')

arr4=np.sort(arr3)
print("The sorted array is:" ,arr4)


Enter the list 1 items: 9 2 10 6 1
Enter the list 2 items: 5 3 7 4 8
The list 1 is: [9, 2, 10, 6, 1]
The list 2 is: [5, 3, 7, 4, 8]

The 1st numpy array is: [[ 9  2 10  6  1]]

The 2nd numpy array is: [[5 3 7 4 8]]

The concatenation of 2 arrays is: [[ 9  2 10  6  1  5  3  7  4  8]]

The sorted array is: [[ 1  2  3  4  5  6  7  8  9 10]]


In [4]:
#Question 3
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )

# Printing type of arr object
print("Array is of type: ", type(arr))

# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)

# Printing shape of array
print("Shape of array: ", arr.shape)

# Printing size (total number of elements) of array
print("Size of array: ", arr.size)

# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int32


In [5]:
#Question 4
a = np.arange(10)
print("The 1-d array is:" ,a)
print(a.shape)
print()
b=a[:, np.newaxis,]
print("The 2-d array using np.newaxis is:" )
print(b)
print(b.shape)
print()
c=np.expand_dims(a,axis=0)
print("The 2-d array using np.expand_dims in x-axis is:")
print(c)
print(c.shape)
print()
d=np.expand_dims(a,axis=1)
print("The 2-d array using np.expand_dims in y-axis is:")
print(d)
print(d.shape)

The 1-d array is: [0 1 2 3 4 5 6 7 8 9]
(10,)

The 2-d array using np.newaxis is:
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(10, 1)

The 2-d array using np.expand_dims in x-axis is:
[[0 1 2 3 4 5 6 7 8 9]]
(1, 10)

The 2-d array using np.expand_dims in y-axis is:
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(10, 1)


In [6]:
#Question 5
arr1=np.array([ [1 ,2, 3] , [4, 5, 6] ,[7, 8, 9]])
arr2=np.array([ [11, 12, 13] , [14 , 15, 16] ,[17, 18, 19]])
sq_arr1=np.square(arr1)
sq_arr2=np.square(arr2)

out_arr1=np.vstack((sq_arr1,sq_arr2))
print(out_arr1)

out_arr2=np.hstack((sq_arr1,sq_arr2))
print(out_arr2)

[[  1   4   9]
 [ 16  25  36]
 [ 49  64  81]
 [121 144 169]
 [196 225 256]
 [289 324 361]]
[[  1   4   9 121 144 169]
 [ 16  25  36 196 225 256]
 [ 49  64  81 289 324 361]]


In [8]:
#Question 6

#USE numpy.unique() TO COUNT THE FREQUENCY OF ALL UNIQUE VALUES IN A LIST
#Call numpy.unique(arr, return_counts=False) with return_count set to True to return a tuple containing the list of unique values in arr and a list of their corresponding frequencies. Use numpy.asarray(a) with this tuple as a to convert it to an array. Use numpy.ndarray.T to transpose this array to reflect the unique values in the original array and their corresponding counts.
import numpy
number_list = numpy.array([1, 1, 2, 3, 4, 4, 1])

(unique, counts) = numpy.unique(number_list, return_counts=True)
frequencies = numpy.asarray((unique, counts)).T

print(frequencies)

[[1 3]
 [2 1]
 [3 1]
 [4 2]]
